name = "eggos"
description = "Bare-metal mobile operating system with Ada/SPARK safety components"
version = "0.1.0"
licenses = ["custom-EOPL"]
authors = ["tunglamtrannguyen3-cmd"]
maintainers = ["tunglamtrannguyen3-cmd"]
website = "https://github.com/tunglamtrannguyen3-cmd/EggOS-for-Mobile"
tags = ["embedded", "os", "aarch64", "bare-metal"]
project-files = ["eggos.gpr"]
